"""
ST-SSL: Self-Supervised Learning for Spatio-Temporal Traffic Prediction.

Paper: Spatio-Temporal Self-Supervised Learning for Traffic Flow Prediction
Link: https://arxiv.org/abs/2212.04475
Reference: https://github.com/Echo-Ji/ST-SSL

This implementation supports:
1. Pre-training mode: Learn representations with contrastive losses
2. Fine-tuning mode: Predict traffic flow with pretrained encoder
3. End-to-end training: Joint training of all components
"""
import torch
import torch.nn as nn

from .encoder import STEncoder, MLP
from .hetero_models import SpatialHeteroModel, TemporalHeteroModel
from .augmentations import aug_topology, aug_traffic


class STSSL(nn.Module):
    """
    ST-SSL: Self-Supervised Learning for Spatio-Temporal Traffic Prediction.

    The model consists of:
    1. STEncoder: Spatio-temporal encoder with Chebyshev graph convolutions
    2. MLP: Prediction head for traffic flow
    3. SpatialHeteroModel: Spatial heterogeneity modeling with prototypes
    4. TemporalHeteroModel: Temporal heterogeneity modeling with discriminator

    Training modes:
    - pretrain: Only contrastive losses (temporal + spatial)
    - finetune: Only prediction loss with frozen encoder
    - end2end: Joint training with all losses
    """

    def __init__(
            self,
            num_nodes: int,
            in_steps: int = 12,
            out_steps: int = 12,
            input_dim: int = 2,
            output_dim: int = 2,
            d_model: int = 64,
            dropout: float = 0.1,
            # Contrastive learning params
            nmb_prototype: int = 10,
            shm_temp: float = 0.5,
            aug_percent: float = 0.2,
            # Loss weights
            loss_weights: list = None,
            # Training mode
            mode: str = 'end2end',  # 'pretrain', 'finetune', 'end2end'
            # Batch size for temporal hetero model
            batch_size: int = 32,
            device: str = 'cuda',
            # Encoder params
            Kt: int = 3,
            Ks: int = 3,
    ):
        """
        Args:
            num_nodes: number of nodes in the graph
            in_steps: input sequence length
            out_steps: output sequence length
            input_dim: input feature dimension
            output_dim: output feature dimension
            d_model: model dimension
            dropout: dropout rate
            nmb_prototype: number of prototypes for spatial hetero model
            shm_temp: temperature for spatial hetero model
            aug_percent: augmentation percentage
            loss_weights: weights for [pred_loss, temporal_loss, spatial_loss]
            mode: training mode ('pretrain', 'finetune', 'end2end')
            batch_size: batch size for temporal hetero model
            device: device to use
            Kt: temporal kernel size
            Ks: spatial kernel size (Chebyshev order)
        """
        super(STSSL, self).__init__()

        self.num_nodes = num_nodes
        self.in_steps = in_steps
        self.out_steps = out_steps
        self.input_dim = input_dim
        self.output_dim = output_dim
        self.d_model = d_model
        self.mode = mode
        self.aug_percent = aug_percent
        self.loss_weights = loss_weights if loss_weights is not None else [1.0, 1.0, 1.0]

        # Encoder blocks configuration
        blocks = [
            [input_dim, int(d_model // 2), d_model],
            [d_model, int(d_model // 2), d_model]
        ]

        # Spatio-temporal encoder
        self.encoder = STEncoder(
            Kt=Kt,
            Ks=Ks,
            blocks=blocks,
            input_length=in_steps,
            num_nodes=num_nodes,
            droprate=dropout
        )

        # Traffic flow prediction branch
        self.mlp = MLP(d_model, output_dim)

        # Temporal heterogeneity modeling branch
        self.thm = TemporalHeteroModel(
            c_in=d_model,
            batch_size=batch_size,
            num_nodes=num_nodes,
            device=device
        )

        # Spatial heterogeneity modeling branch
        self.shm = SpatialHeteroModel(
            c_in=d_model,
            nmb_prototype=nmb_prototype,
            batch_size=batch_size,
            tau=shm_temp
        )

        # Store adjacency matrix
        self.register_buffer('adj_mx', None)

    def set_adj_matrix(self, adj_mx: torch.Tensor):
        """Set the adjacency matrix for the model."""
        if isinstance(adj_mx, torch.Tensor):
            self.register_buffer('adj_mx', adj_mx.float())
        else:
            self.register_buffer('adj_mx', torch.tensor(adj_mx).float())

    def fetch_spatial_sim(self) -> torch.Tensor:
        """
        Fetch the region similarity matrix generated by region embedding.

        Returns:
            sim_mx: tensor, similarity matrix, (v, v)
        """
        return self.encoder.s_sim_mx

    def fetch_temporal_sim(self) -> torch.Tensor:
        """
        Fetch the temporal similarity matrix.

        Returns:
            t_sim_mx: tensor, temporal similarity matrix
        """
        return self.encoder.t_sim_mx

    def encode(self, view: torch.Tensor, graph: torch.Tensor) -> torch.Tensor:
        """
        Encode input through the ST encoder.

        Args:
            view: input tensor, [n, l, v, c]
            graph: adjacency matrix, [v, v]

        Returns:
            representation tensor, [n, 1, v, d_model]
        """
        return self.encoder(view, graph)

    def predict(self, z: torch.Tensor) -> torch.Tensor:
        """
        Predict future traffic flow from representations.

        Args:
            z: representation tensor, [n, 1, v, d_model]

        Returns:
            prediction tensor, [n, out_steps, v, output_dim]
        """
        # z: [n, 1, v, d_model] -> [n, out_steps, v, output_dim]
        pred = self.mlp(z)  # [n, 1, v, output_dim]

        # Expand to out_steps if needed
        if pred.size(1) == 1 and self.out_steps > 1:
            pred = pred.expand(-1, self.out_steps, -1, -1)

        return pred

    def forward(
            self,
            history_data: torch.Tensor,
            future_data: torch.Tensor = None,
            batch_seen: int = None,
            epoch: int = None,
            train: bool = True,
            **kwargs
    ):
        """
        Forward pass of ST-SSL.

        Args:
            history_data: input tensor, [B, L, N, C]
            future_data: target tensor (unused in forward, used for loss)
            batch_seen: number of batches seen
            epoch: current epoch
            train: whether in training mode

        Returns:
            If train=True: dict with 'prediction' and losses
            If train=False: prediction tensor [B, out_steps, N, output_dim]
        """
        # Get adjacency matrix
        if 'adj_mx' in kwargs and kwargs['adj_mx'] is not None:
            adj_mx = kwargs['adj_mx']
            if not isinstance(adj_mx, torch.Tensor):
                adj_mx = torch.tensor(adj_mx, device=history_data.device, dtype=torch.float)
        else:
            adj_mx = self.adj_mx.to(history_data.device)

        # Select input features if needed
        if history_data.size(-1) > self.input_dim:
            view1 = history_data[..., :self.input_dim]
        else:
            view1 = history_data

        # Encode view 1
        repr1 = self.encode(view1, adj_mx)

        if train and self.mode in ['pretrain', 'end2end']:
            # Generate augmented views
            s_sim_mx = self.fetch_spatial_sim()
            if s_sim_mx is not None:
                graph2 = aug_topology(s_sim_mx, adj_mx, percent=self.aug_percent * 2)
            else:
                graph2 = adj_mx

            t_sim_mx = self.fetch_temporal_sim()
            if t_sim_mx is not None:
                view2 = aug_traffic(t_sim_mx, view1, percent=self.aug_percent)
            else:
                view2 = view1

            # Encode view 2
            repr2 = self.encode(view2, graph2)

            # Compute prediction
            prediction = self.predict(repr1)

            # Return dict with representations for loss computation
            return {
                'prediction': prediction,
                'repr1': repr1,
                'repr2': repr2,
            }
        else:
            # Inference mode: just predict
            prediction = self.predict(repr1)
            return prediction

    def compute_ssl_losses(self, repr1: torch.Tensor, repr2: torch.Tensor):
        """
        Compute self-supervised learning losses.

        Args:
            repr1: representation from view 1, [n, 1, v, d_model]
            repr2: representation from view 2, [n, 1, v, d_model]

        Returns:
            temporal_loss, spatial_loss
        """
        temporal_loss = self.thm(repr1, repr2)
        spatial_loss = self.shm(repr1, repr2)
        return temporal_loss, spatial_loss


class STSSLWrapper(nn.Module):
    """
    Wrapper for STSSL that handles BasiCTS integration.

    This wrapper:
    1. Manages adjacency matrix loading
    2. Handles different training modes
    3. Provides clean interface for BasiCTS runners
    """

    def __init__(
            self,
            num_nodes: int,
            in_steps: int = 12,
            out_steps: int = 12,
            input_dim: int = 3,
            output_dim: int = 1,
            d_model: int = 64,
            dropout: float = 0.1,
            nmb_prototype: int = 10,
            shm_temp: float = 0.5,
            aug_percent: float = 0.2,
            loss_weights: list = None,
            mode: str = 'end2end',
            batch_size: int = 32,
            Kt: int = 3,
            Ks: int = 3,
            **kwargs
    ):
        super(STSSLWrapper, self).__init__()

        # The actual STSSL model uses first `stssl_input_dim` features
        # (typically speed/flow, not time features)
        stssl_input_dim = kwargs.get('stssl_input_dim', 1)
        stssl_output_dim = kwargs.get('stssl_output_dim', 1)

        self.input_dim = input_dim
        self.stssl_input_dim = stssl_input_dim
        self.output_dim = output_dim

        self.model = STSSL(
            num_nodes=num_nodes,
            in_steps=in_steps,
            out_steps=out_steps,
            input_dim=stssl_input_dim,
            output_dim=stssl_output_dim,
            d_model=d_model,
            dropout=dropout,
            nmb_prototype=nmb_prototype,
            shm_temp=shm_temp,
            aug_percent=aug_percent,
            loss_weights=loss_weights,
            mode=mode,
            batch_size=batch_size,
            device='cuda' if torch.cuda.is_available() else 'cpu',
            Kt=Kt,
            Ks=Ks,
        )

        self.mode = mode
        self.loss_weights = loss_weights if loss_weights is not None else [1.0, 1.0, 1.0]

    def set_adj_matrix(self, adj_mx):
        """Set adjacency matrix."""
        self.model.set_adj_matrix(adj_mx)

    def forward(
            self,
            history_data: torch.Tensor,
            future_data: torch.Tensor = None,
            batch_seen: int = None,
            epoch: int = None,
            train: bool = True,
            **kwargs
    ):
        """Forward pass with BasiCTS interface."""
        return self.model(
            history_data=history_data,
            future_data=future_data,
            batch_seen=batch_seen,
            epoch=epoch,
            train=train,
            **kwargs
        )
