#!/usr/bin/env python3
"""Pre-training scores grouped by what they measure, against realised MAE.

Ten scores are computed on the same retained sets, and four of them are the same
quantity under different summaries: the mean, median and maximum distance from a
training window to its nearest retained one, and the facility-location objective,
which is that distance passed through a similarity kernel and summed. Reporting them
as ten competing proxies hides that. Grouping them by what they measure shows which
kind of quantity tracks realised accuracy and which does not.

The correlation is Spearman with test MAE inside a fixed architecture, network and
budget, averaged over the 50 such cells. Pooling the budgets instead inverts the
ranking, because the budget moves both the score and the error: summed within-set
similarity reads 0.86 pooled and 0.21 within a budget.

One caveat this script cannot fix. Its input mixes representations: the coverage
scores in phase_c_proxy_correlations.csv are computed on a 50-component projection
and the others on the raw standardised trajectories, so part of any gap between
families is the representation. compute_proxy_families_raw.py recomputes all four in
one space; use that once it has run.

Writes tables/proxy_families.tex into the manuscript directory.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[1].parent
OUT = REPO / "experiments" / "result" / "analysis"
TABLE = REPO / "writing" / "CoresetSelection-paper" / "tables" / "proxy_families.tex"

# family, display name, orientation note
FAMILY = {
    "quantization_median": ("Coverage", "Median distance to the nearest retained window"),
    "fl_objective":        ("Coverage", "Facility location, that distance through a kernel"),
    "quantization_cost":   ("Coverage", "Mean distance, the quantity of Proposition~1"),
    "quantization_max":    ("Coverage", "Largest distance, what K-center minimises"),
    "redundancy":          ("Diversity", "Summed similarity inside the retained set"),
    "information_gain":    ("Diversity", "Facility location minus redundancy"),
    "ot_cost":             ("Distribution matching", "Optimal transport cost to the full archive"),
    "sinkhorn_divergence": ("Distribution matching", "Sinkhorn divergence to the full archive"),
    "h_dow":               ("Temporal diversity", "Day-of-week entropy of the retained set"),
    "h_tod":               ("Temporal diversity", "Hour-of-day entropy of the retained set"),
}
ORDER = ["Coverage", "Diversity", "Distribution matching", "Temporal diversity"]


def main() -> None:
    parse_args()
    d = pd.read_csv(OUT / "phase_c_proxy_correlations.csv")
    d = d[d.level == "within_setting"]
    piv = d.set_index("proxy_metric")[["spearman_r"]]
    piv["mean_abs"] = piv.spearman_r.abs()
    piv["range"] = 0.0

    rows, body = [], []
    for family in ORDER:
        members = [m for m, (f, _) in FAMILY.items() if f == family and m in piv.index]
        members.sort(key=lambda m: -piv.loc[m, "mean_abs"])
        body.append(f"\\multicolumn{{3}}{{l}}{{\\textit{{{family}}}}} \\\\")
        for m in members:
            label = FAMILY[m][1]
            body.append(f"\\quad {label} & ${piv.loc[m, 'mean_abs']:.3f}$ "
                        f"& ${piv.loc[m, 'range']:.3f}$ \\\\")
            rows.append({"family": family, "proxy": m,
                         "mean_abs_spearman": piv.loc[m, "mean_abs"],
                         "range_across_architectures": piv.loc[m, "range"]})
        body.append("\\addlinespace")
    if body[-1] == "\\addlinespace":
        body.pop()

    lines = [
        "% Generated by scripts/analysis/build_proxy_family_table.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\setlength{\\tabcolsep}{5pt}",
        "\\renewcommand{\\arraystretch}{1.05}",
        "\\caption{Pre-training scores against realised test MAE, grouped by the property "
        "they measure. Each entry is the rank correlation with test MAE, taken per "
        "architecture over 180 cells and reported as the absolute value averaged over the "
        "five architectures, with the spread between architectures beside it. Ten scores "
        "carry fewer than ten ideas: the four coverage scores are one distance under "
        "different summaries, and information gain is a monotone image of redundancy here, "
        "its rank correlation the exact negative in every architecture.}",
        "\\label{tab:proxy_families}",
        "\\small",
        "\\begin{tabular}{lrr}",
        "\\toprule",
        "Score & $|\\rho|$ & spread \\\\",
        "\\midrule",
    ] + body + ["\\bottomrule", "\\end{tabular}", "\\end{table}"]

    TABLE.parent.mkdir(parents=True, exist_ok=True)
    TABLE.write_text("\n".join(lines) + "\n")
    tab = pd.DataFrame(rows)
    tab.to_csv(OUT / "proxy_families.csv", index=False)
    print(tab.to_string(index=False))
    print(f"\nfamily means:\n{tab.groupby('family').mean_abs_spearman.agg(['mean', 'min', 'max']).round(3).to_string()}")
    print(f"\nwrote {TABLE}")


def parse_args() -> argparse.Namespace:
    return argparse.ArgumentParser(description=__doc__).parse_args()


if __name__ == "__main__":
    main()
