#!/usr/bin/env python3
"""Main accuracy table, reported by traffic state as well as in aggregate.

The manuscript argues that a reduced training set must be reported by traffic state,
because the aggregate is blind to the state that loses the most. The main results
table should therefore practise that. For each selection objective this script
reports the MAE increase over full-data training, aggregated as before and then
conditioned on the four detector-resolved transitions.

The aggregate column is the increase over all detectors and windows, as in the
previous version of the table. The state columns are computed on the screened
detectors that carry a fitted critical point, so they are shares of a different
population and are comparable across objectives, not against the aggregate.

Writes tables/accuracy_summary.tex into the manuscript directory.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[1].parent
OUT = REPO / "experiments" / "result" / "analysis"
TABLE = REPO / "writing" / "CoresetSelection-paper" / "tables" / "accuracy_summary.tex"

ORDER = [("random", "Random"), ("recent", "Recent"), ("stride", "Stride"),
         ("k_medoids", "K-medoids"), ("k_center", "K-center"), ("graph_cut", "Graph Cut")]
STATES = [("free", "Free flow"), ("breakdown", "Breakdown"),
          ("recovery", "Recovery"), ("sustained", "Congestion")]


def aggregate_increase() -> pd.DataFrame:
    """Percentage MAE increase over full data, averaged over models, ratios, networks."""
    unified = pd.read_csv(REPO / "experiments" / "result" / "unified_mae_table.csv")
    full = (unified[np.isclose(unified.ratio, 1.0)]
            .groupby(["dataset", "model"], as_index=False).MAE.mean()
            .rename(columns={"MAE": "mae_full"}))
    red = unified[unified.ratio < 1.0].merge(full, on=["dataset", "model"], how="inner")
    red["increase"] = 100.0 * (red.MAE - red.mae_full) / red.mae_full
    # rank objectives inside each dataset-model-ratio block
    red["rank"] = red.groupby(["dataset", "model", "ratio"]).MAE.rank()
    return red.groupby("method", as_index=False).agg(
        aggregate=("increase", "mean"), mean_rank=("rank", "mean"))


def state_increase() -> pd.DataFrame:
    """Percentage MAE increase over full data within each state, same averaging."""
    d = pd.read_csv(OUT / "fd_selection_experiment_summary.csv")
    full = (d[d.method == "full"][["dataset", "backbone", "state", "mae"]]
            .rename(columns={"mae": "ref"}))
    red = d[(d.method != "full") & (d.ratio < 1.0)].drop(
        columns=[c for c in d.columns if c.startswith("mae_full")], errors="ignore").merge(
        full, on=["dataset", "backbone", "state"], how="inner")
    red["increase"] = red.mae - red.ref          # MAE units, not per cent
    return (red.groupby(["method", "state"], as_index=False).increase.mean()
            .pivot(index="method", columns="state", values="increase"))


def main() -> None:
    parse_args()
    agg = aggregate_increase().set_index("method")
    st = state_increase()

    rows = []
    for key, label in ORDER:
        if key not in agg.index:
            continue
        cells = [f"{agg.loc[key, 'aggregate']:+.1f}\\%"]
        for scode, _ in STATES:
            v = st.loc[key, scode] if key in st.index and scode in st.columns else np.nan
            cells.append("---" if not np.isfinite(v) else f"{v:+.2f}")
        cells.append(f"{agg.loc[key, 'mean_rank']:.2f}")
        rows.append(f"{label:<10} & " + " & ".join(cells) + " \\\\")

    best_agg = agg['aggregate'].idxmin()
    lines = [
        "% Generated by scripts/analysis/build_accuracy_summary_by_state.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\setlength{\\tabcolsep}{4pt}",
        "\\renewcommand{\\arraystretch}{1.06}",
        "\\caption{MAE increase over full-data training, averaged over five architectures, "
        "five sampling ratios and two networks. The aggregate column covers all detectors "
        "and windows. The state columns cover the screened detectors that carry a fitted "
        "critical point, so they compare objectives with each other and not with the "
        "aggregate. Mean rank is taken within each network--architecture--ratio block, "
        "lower is better. The aggregate separates the objectives and the breakdown column does not, since five of the six lie within $0.16$ MAE of each other there while their aggregate increases span a factor of two.}",
        "\\label{tab:accuracy_summary}",
        "\\small",
        "\\begin{tabular}{lrrrrrr}",
        "\\toprule",
        " & & \\multicolumn{4}{c}{By traffic state} & \\\\",
        "\\cmidrule(lr){3-6}",
        "Objective & Aggregate & Free & Breakdown & Recovery & Congestion & Mean rank \\\\",
        " & (\\%) & (MAE) & (MAE) & (MAE) & (MAE) & \\\\",
        "\\midrule",
    ]
    lines += rows
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]
    TABLE.write_text("\n".join(lines) + "\n")

    print(agg.join(st).round(2).to_string())
    print(f"\nlowest aggregate increase: {best_agg}")
    print(f"wrote {TABLE}")


def parse_args() -> argparse.Namespace:
    return argparse.ArgumentParser(description=__doc__).parse_args()


if __name__ == "__main__":
    main()
