#!/usr/bin/env python3
"""LaTeX table for the breakdown-coverage frontier.

Reads fd_selection_experiment_summary.csv and writes tables/fd_selection_frontier.tex
into the manuscript directory.  One row per selection objective, ordered by the share of
breakdown atoms it retains; columns pair what the objective buys on the selection side
with what it costs on the outcome side.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

REPO = Path(__file__).resolve().parents[2]
SUMMARY = REPO / "experiments" / "result" / "analysis" / "fd_selection_experiment_summary.csv"
TABLE = REPO / "writing" / "CoresetSelection-paper" / "tables" / "fd_selection_frontier.tex"

LABEL = {
    "random": "Random", "stride": "Stride", "k_medoids": "K-medoids", "graph_cut": "Graph Cut",
    "fd_grp10": "Group-balanced ($\\beta=1$)", "fd_grp05": "Group-balanced ($\\beta=0.5$)",
    "fd_grp00": "Group-balanced ($\\beta=0$)",
    "fd_hyb0802": "Split budget ($0.08+0.02$)", "fd_hyb0604": "Split budget ($0.06+0.04$)",
    "fd_strat00": "Stratified allocation", "oracle_breakdown_count": "Breakdown-count ranking",
}
ORDER = ["random", "stride", "k_medoids", "graph_cut", "fd_grp10", "fd_grp05", "fd_grp00",
         "fd_hyb0802", "fd_hyb0604", "fd_strat00"]


def build(df: pd.DataFrame, dataset: str) -> list[str]:
    sub = df[(df.dataset == dataset) & (df.method != "full")]
    bd = sub[sub.state == "breakdown"]
    free = sub[sub.state == "free"].set_index(["method", "backbone"])
    rows = []
    for method in ORDER:
        cells = bd[bd.method == method]
        if cells.empty:
            continue
        cov = cells.coverage_breakdown.iloc[0]
        cov_free = cells.coverage_free.iloc[0]
        tv = cells.calendar_tv.iloc[0]
        deg_bd = cells.degradation.mean()
        bias_bd = cells.bias.mean()
        fr = sub[(sub.method == method) & (sub.state == "free")]
        deg_free = fr.degradation.mean()
        n = cells.backbone.nunique()
        rows.append(f"{LABEL[method]} & {cov:.3f} & {cov_free:.3f} & {tv:.2f} & "
                    f"{deg_bd:.2f} & {bias_bd:.1f} & {deg_free:.2f} & {n} \\\\")
    return rows


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--summary", type=Path, default=SUMMARY)
    parser.add_argument("--out", type=Path, default=TABLE)
    args = parser.parse_args()

    df = pd.read_csv(args.summary)
    lines = [
        "% Generated by scripts/analysis/build_selection_frontier_table.py",
        "\\begin{table}[t]",
        "\\centering",
        "\\caption{"
        "Selection against outcome at $r=0.1$, over five architectures in each network. The "
        "left block is computed on the chronological training split before any model is "
        "fitted, and gives the share of each state's window--detector pairs the objective "
        "retains, and the joint total variation of its hour-of-day and day-of-week "
        "distribution from the full training set. The right block is the state-conditional "
        "reduction loss minus that of Random, so a negative entry is an improvement. Random's "
        "own losses are $2.84$, $5.47$, $3.31$, $1.64$ MAE on San Bernardino and $2.79$, "
        "$6.18$, $3.29$, $2.16$ on Contra Costa.}",
        "\\label{tab:selection_frontier}",
        "\\begin{tabular}{lrrrrrrr}",
        "\\toprule",
        " & \\multicolumn{3}{c}{Selection} & \\multicolumn{3}{c}{Outcome (MAE)} & \\\\",
        "\\cmidrule(lr){2-4}\\cmidrule(lr){5-7}",
        "Objective & breakdown & free & TV & $\\Delta$ bd & bias bd & $\\Delta$ free & $n$ \\\\",
        "\\midrule",
    ]
    for dataset in ("SAN_BERNARDINO", "CONTRA_COSTA"):
        body = build(df, dataset)
        if not body:
            continue
        name = dataset.replace("_", " ").title()
        lines.append(f"\\multicolumn{{8}}{{l}}{{\\textit{{{name}}}}} \\\\")
        lines.extend(body)
        lines.append("\\midrule")
    if lines[-1] == "\\midrule":
        lines.pop()
    lines += ["\\bottomrule", "\\end{tabular}", "\\end{table}"]

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
