#!/usr/bin/env python3
"""The attainable retention frontier, and where the audited objectives sit on it.

Two tables. The first is the frontier itself: the largest breakdown retention a budget
of windows admits while holding free-flow retention at or above tau, with the bracket
between the linear-programming value and the feasible set one exchange returns, and
the same quantity when congestion is the guarded state instead. The second places each
objective at its own realised free-flow retention, so the comparison is against the
bound that objective actually faces and not against a corner it never approached.

Reads experiments/result/analysis/attainable_allocation{,_selectors}.csv.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np
import pandas as pd

REPO = Path(__file__).resolve().parents[2]
OUT = REPO / "experiments" / "result" / "analysis"
TABLES = REPO / "writing" / "CoresetSelection-paper" / "tables"
LABEL = {"random": "Random", "stride": "Stride", "recent": "Recent",
         "k_medoids": "K-medoids", "k_center": "K-center", "graph_cut": "Graph Cut",
         "fd_grp00": "Quota, $\\beta=0$", "fd_strat00": "Stratified allocation",
         "fd_hyb0802": "Split $0.08+0.02$", "fd_hyb0604": "Split $0.06+0.04$",
         "fd_front10": "Frontier set, $\\tau=0.10$"}
ORDER = ["random", "stride", "recent", "k_medoids", "k_center", "graph_cut",
         "fd_grp00", "fd_hyb0802", "fd_hyb0604", "fd_strat00", "fd_front10"]


def frontier_table(f: pd.DataFrame, ratio: float) -> str:
    free = f[(f.target == "breakdown") & (f.guarded == "free") & (f.ratio == ratio)]
    cong = f[(f.target == "breakdown") & (f.guarded == "congestion") & (f.ratio == ratio)]
    taus = sorted(free.tau.unique())
    rows = []
    for dataset, name in (("SAN_BERNARDINO", "San Bernardino"), ("CONTRA_COSTA", "Contra Costa")):
        rows.append(f"\\multicolumn{{{len(taus) + 1}}}{{l}}{{\\textit{{{name}}}}} \\\\")
        for guard, block in (("free flow", free), ("congestion", cong)):
            g = block[block.dataset == dataset].set_index("tau")
            cells = []
            for tau in taus:
                value = g.lp.get(tau, np.nan)
                cells.append("--" if not np.isfinite(value) else f"${value:.3f}$")
            rows.append(f"\\quad guard {guard} & " + " & ".join(cells) + " \\\\")
        g = free[free.dataset == dataset]
        rows.append(f"\\quad bracket width & "
                    + " & ".join("--" if not np.isfinite(v) else f"${v:.4f}$"
                                 for v in (g.set_index("tau").gap.get(t, np.nan) for t in taus))
                    + " \\\\")
        rows.append("\\addlinespace")
    rows.pop()
    header = " & ".join(f"${t:g}$" for t in taus)
    certificate = free.certificate.dropna().max()
    largest = free.groupby("dataset").max_guarded.first()
    return "\n".join([
        "% Generated by scripts/analysis/build_frontier_table.py",
        "\\begin{table}[t]", "\\centering", "\\setlength{\\tabcolsep}{4pt}",
        "\\renewcommand{\\arraystretch}{1.05}",
        "\\caption{The largest breakdown retention a budget of "
        f"$r={ratio:g}$ admits while the guarded state is held at or above $\\tau$, from the "
        "linear programme of Proposition~\\ref{prop:frontier}. Entries are the relaxation "
        "value. The bracket width is what the one-exchange rounding loses, against an "
        f"a-priori bound of ${certificate:.4f}$, one window's worth of the state. A dash marks "
        "a guard level no budget of this size can reach. The largest free-flow retention "
        f"available is ${largest['SAN_BERNARDINO']:.3f}$ and ${largest['CONTRA_COSTA']:.3f}$. "
        "Guarding congestion in place of free flow costs nothing until $\\tau$ passes $0.15$, "
        "because the windows carrying breakdown carry congestion with it.}",
        "\\label{tab:attainable_frontier}", "\\small",
        "\\begin{tabular}{l" + "r" * len(taus) + "}", "\\toprule",
        f"$\\tau$ & {header} \\\\", "\\midrule", *rows,
        "\\bottomrule", "\\end{tabular}", "\\end{table}"]) + "\n"


def objective_table(s: pd.DataFrame, ratio: float) -> str:
    d = s[(s.target == "breakdown") & (s.guarded == "free") & (s.ratio == ratio)]
    rows = []
    for dataset, name in (("SAN_BERNARDINO", "San Bernardino"), ("CONTRA_COSTA", "Contra Costa")):
        g = d[d.dataset == dataset].set_index("objective")
        rows.append(f"\\multicolumn{{5}}{{l}}{{\\textit{{{name}}}}} \\\\")
        for key in ORDER:
            if key not in g.index:
                continue
            r = g.loc[key]
            binds = "yes" if r.guard_binds else "no"
            rows.append(f"\\quad {LABEL.get(key, key)} & ${r.pi_guarded:.3f}$ & "
                        f"${r.pi_target:.3f}$ & ${r.lp_at_pi_guarded:.3f}$ & "
                        f"${r.attained_share:.2f}$ \\\\")
        rows.append("\\addlinespace")
    rows.pop()
    return "\n".join([
        "% Generated by scripts/analysis/build_frontier_table.py",
        "\\begin{table}[t]", "\\centering", "\\setlength{\\tabcolsep}{5pt}",
        "\\renewcommand{\\arraystretch}{1.05}",
        "\\caption{Each objective against the bound it faces at $r=" f"{ratio:g}" "$. The bound "
        "is evaluated at that objective's own realised free-flow retention, so objectives that "
        "give up free flow are compared against the larger breakdown retention that giving it "
        "up permits. The last column is the ratio of the two, the share of what was available "
        "that the objective reached.}",
        "\\label{tab:frontier_objectives}", "\\small",
        "\\begin{tabular}{lrrrr}", "\\toprule",
        "Objective & $\\pi_{\\mathrm{free}}$ & $\\pi_{\\mathrm{bd}}$ & bound & share \\\\",
        "\\midrule", *rows, "\\bottomrule", "\\end{tabular}", "\\end{table}"]) + "\n"


def main() -> None:
    args = parse_args()
    f = pd.read_csv(OUT / "attainable_allocation.csv")
    s = pd.read_csv(OUT / "attainable_allocation_selectors.csv")
    TABLES.mkdir(parents=True, exist_ok=True)
    (TABLES / "attainable_frontier.tex").write_text(frontier_table(f, args.ratio))
    (TABLES / "frontier_objectives.tex").write_text(objective_table(s, args.ratio))
    print(f"wrote {TABLES / 'attainable_frontier.tex'}")
    print(f"wrote {TABLES / 'frontier_objectives.tex'}")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--ratio", type=float, default=0.1)
    return parser.parse_args()


if __name__ == "__main__":
    main()
